[Logging]
test_log_collect=false

[Logging.LogStream]
log_targets=["file"]
log_producer_timeout="10s"
log_producer_retry_limit=10

[Network]
selected_networks=["SIMULATED"] # Not needed for Starknet but mandatory from CTF

[Network.RpcHttpUrls]
simulated = ["http://127.0.0.1"] # Not needed for Starknet but mandatory from CTF

[Network.RpcWsUrls]
simulated = ["wss://127.0.0.1"] # Not needed for Starknet but mandatory from CTF

[Common]
inside_k8 = false
network = "localnet"

[OCR2]
node_count = 6
test_duration = "30m"

[OCR2.Smoke]
number_of_rounds = 10
