# Declare variables to be passed into your templates.
replicaCount: 1
service:
  name: starknet-service
  type: ClusterIP
  externalPort: 5000
  internalPort: 5000
resources:
  limits:
    cpu: 5000m
    memory: 5120Mi
  requests:
    cpu: 5000m
    memory: 5120Mi
url_http_L1: ""
real_node: false
seed: 123