name: Install Cairo and Scarb
description: A composite action that installs cairo binaries

inputs:
  cairo_version:
    description: Cairo release version
    default: "v1.1.0"
    required: false

runs:
  using: composite
  steps:
    - name: Setup Cairo for Linux
      id: install-cairo
      shell: bash
      run: |
        wget https://github.com/starkware-libs/cairo/releases/download/${{ inputs.cairo_version }}/release-x86_64-unknown-linux-musl.tar.gz
        tar -xvzf release-x86_64-unknown-linux-musl.tar.gz
        mv -vf cairo cairo-build
        echo "$GITHUB_WORKSPACE/cairo-build/bin" >> $GITHUB_PATH
