name: Integration Tests - Soak

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      cl_branch_ref:
        description: Chainlink repo branch to integrate with
        required: true
        default: develop
        type: string
      l2_rpc_url:
        description: Override default RPC url which points to local devnet (Optional)
        required: false
        type: string
      node_count:
        description: Number of ocr nodes
        required: true
        default: 5
        type: string
      ttl:
        description: TTL for namespace
        required: true
        default: 72h
        type: string



# Only run 1 of this workflow at a time per PR
concurrency:
  group: integration-tests-starknet-${{ github.ref }}
  cancel-in-progress: true

env:
  REF_NAME: ${{ github.head_ref || github.ref_name }}
  ENV_JOB_IMAGE: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink-starknet-tests:${{ github.head_ref || github.ref_name }}

jobs:
  build_custom_chainlink_image:
    name: Build Custom CL Image
    runs-on: ubuntu-latest
    environment: integration
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Build Image
        uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/build-image@ce87f8986ca18336cc5015df75916c2ec0a7c4b3 # v2.1.2
        with:
          cl_repo: smartcontractkit/chainlink
          # By default we are integrating with CL develop
          cl_ref: ${{ github.event.inputs.cl_branch_ref }}
          # commit of the caller branch
          dep_starknet_sha: ${{ github.event.pull_request.head.sha || github.sha }}
          push_tag: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink:custom.${{ github.sha }}
          QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
          QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
          QA_PRIVATE_GHA_PULL: ${{ secrets.QA_PRIVATE_GHA_PULL }}

  run_tests:
    name: Run Soak Tests
    runs-on: ubuntu-latest
    needs: [ build_custom_chainlink_image ]
    environment: integration
    env:
      CHAINLINK_ENV_USER: ${{ github.actor }}
      L2_RPC_URL: ${{ github.event.inputs.l2_rpc_url }}
      NODE_COUNT: ${{ github.event.inputs.node_count }}
      CL_IMAGE: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink
      CL_VERSION: custom.${{ github.sha }}
      PRIVATE_KEY: ${{ secrets.GOERLI_PRIVATE_KEY }}
      ACCOUNT: ${{ secrets.GOERLI_ACCOUNT }}
      TTL: ${{ github.event.inputs.ttl }}
    permissions:
      checks: write
      pull-requests: write
      id-token: write
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3.0.2
      - name: Install Nix
        uses: cachix/install-nix-action@d64e0553100205688c0fb2fa16edb0fc8663c590 # v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build Test Runner
        if: ${{ env.REF_NAME != 'develop' }}
        uses: smartcontractkit/chainlink-github-actions/docker/build-push@ce87f8986ca18336cc5015df75916c2ec0a7c4b3 # v2.1.2
        with:
          tags: ${{ env.ENV_JOB_IMAGE }}
          file: ./integration-tests/test.Dockerfile
          build-args: |
            BASE_IMAGE=${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/test-base-image
            IMAGE_VERSION=v0.3.18
            SUITES="soak"
          AWS_REGION: ${{ secrets.QA_AWS_REGION }}
          AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
      - name: Run Tests
        uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/run-tests@ce87f8986ca18336cc5015df75916c2ec0a7c4b3 # v2.1.2
        with:
          test_command_to_run: nix develop -c make test-integration-soak-ci
          test_download_vendor_packages_command: cd integration-tests && nix develop -c go mod download
          cl_repo: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink
          cl_image_tag: custom.${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          go_mod_path: ./integration-tests/go.mod
          QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
          QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
          QA_KUBECONFIG: ${{ secrets.QA_KUBECONFIG }}
