name: Lint

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  lint_format_check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - name: Install Nix
        uses: cachix/install-nix-action@d64e0553100205688c0fb2fa16edb0fc8663c590 # v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install
        run: nix develop -c yarn install --frozen-lockfile

      - name: Check
        run: nix develop -c make format-check

  lint_go_ops:
    name: Lint go ops
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - name: Install Nix
        uses: cachix/install-nix-action@d64e0553100205688c0fb2fa16edb0fc8663c590 # v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Lint ops
        run: nix develop -c make lint-go-ops

  lint_go_relayer:
    name: Lint go relayer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - name: Install Nix
        uses: cachix/install-nix-action@d64e0553100205688c0fb2fa16edb0fc8663c590 # v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Lint relayer
        run: nix develop -c make lint-go-relayer

  lint_go_integration_tests:
    name: Lint go integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - name: Install Nix
        uses: cachix/install-nix-action@d64e0553100205688c0fb2fa16edb0fc8663c590 # v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Lint integration-tests
        run: nix develop -c make lint-go-test
