name: Lint

on:
  push:
    branches:
      - develop
      - main
  pull_request:

env:
  CAIRO_VERSION: v1.0.0-alpha.6

jobs:
  lint_format_check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Install Nix
        uses: cachix/install-nix-action@29bd9290ef037a3ecbdafe83cbd2185e9dd0fa0a # v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Cairo for Linux
        run: |
          wget https://github.com/starkware-libs/cairo/releases/download/${{ env.CAIRO_VERSION }}/release-x86_64-unknown-linux-musl.tar.gz
          tar -xvzf release-x86_64-unknown-linux-musl.tar.gz
          echo "$GITHUB_WORKSPACE/cairo/bin" >> $GITHUB_PATH

      - name: Install
        run: nix develop -c yarn install --frozen-lockfile

      - name: Check
        run: nix develop -c make format-check
